[theme]
# Primary accent color for interactive elements.
primaryColor = "#9b3b84"

# Background color for the main content area.
backgroundColor = "#e1edf1"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#cadbe8"

# Color used for almost all text.
textColor = "#2f3d4e"